
import React, { useState, useEffect, useRef } from 'react';
import type { View } from '../types.ts';
import { BlueprintIcon, ArrowUpIcon } from './Icons.tsx';

interface SampleReportProps {
    onViewChange: (view: View) => void;
}

export const SampleReport: React.FC<SampleReportProps> = ({ onViewChange }) => {
    const [showScroll, setShowScroll] = useState(false);
    const viewContainerRef = useRef<HTMLDivElement | null>(null);

    const checkScrollTop = () => {
        if (viewContainerRef.current && viewContainerRef.current.scrollTop > 300) {
            setShowScroll(true);
        } else {
            setShowScroll(false);
        }
    };

    const scrollTop = () => {
        viewContainerRef.current?.scrollTo({ top: 0, behavior: 'smooth' });
    };

    useEffect(() => {
        const container = document.querySelector('.view-container');
        if (container) {
            viewContainerRef.current = container as HTMLDivElement;
            container.addEventListener('scroll', checkScrollTop);
        }
        return () => {
             if (viewContainerRef.current) {
                viewContainerRef.current.removeEventListener('scroll', checkScrollTop);
             }
        }
    }, []);

    return (
        <div className="max-w-5xl mx-auto p-4 md:p-8">
            <header className="text-center mb-8">
                <h2 className="text-4xl font-extrabold text-nexus-text-primary tracking-tighter">Engineering Global-Regional Symbiosis</h2>
                <p className="mt-4 text-lg text-nexus-text-secondary max-w-3xl mx-auto">
                    We are a dedicated intelligence partner, built to translate raw data into strategic foresight for regional economic development.
                </p>
            </header>
            
            <div className="p-4 bg-nexus-surface-700 border border-nexus-border-medium rounded-lg text-nexus-text-secondary text-sm mb-6">
                <h3 className="font-bold text-nexus-text-primary">Note on this Sample Blueprint</h3>
                <p>This is a sample report generated by the Nexus AI engine to demonstrate its structure and analytical capabilities. All names, locations, and specific financial figures have been altered for privacy and demonstration purposes. Your own generated reports will be tailored to your specific inputs.</p>
            </div>
            
            <div className="report-document-container shadow-2xl">
                <header className="blueprint-header">
                    <p className="text-sm text-nexus-text-secondary">FORMAL PROPOSAL & INVITATION</p>
                    <h1 className="text-3xl font-extrabold text-nexus-text-primary mt-1">Fuel Storage and Bunkering Facility at Mariposa Port</h1>
                </header>

                <div className="blueprint-content">
                    <p><strong>Dear [Company Representative],</strong></p>
                    <p>On behalf of Mayor Isabel Santos of the City of Mariposa, I extend a formal invitation for your company to evaluate Mariposa Port as the site for establishing a dedicated fuel storage and bunkering facility. This project represents the first compliant refueling infrastructure for the southern region and is intended to improve logistics reliability, reduce costly diversions, and create a platform for future regional growth.</p>
                    <p>Mariposa offers a naturally protected bay with lower exposure to major typhoons, a growing pattern of vessel traffic, and a local government committed to fast-tracking permits, providing security coordination (police, Coast Guard), and facilitating investor engagement.</p>
                    
                    <h2>Executive Summary & Current Situation</h2>
                    <p>This assessment provides an early-stage technical and commercial outline for establishing the first compliant bunkering facility at Mariposa Port. It is structured to give clear guidance on recommended fuel types, storage approaches, structural and safety requirements, and the regulatory pathway.</p>
                    <h3>Current Port Activity & Estimated Demand</h3>
                    <p>Based on local port logs and BWGA field observations, Mariposa currently handles approximately 30-40 vessel calls per month. Using conservative composition assumptions, a representative monthly fuel demand estimate is approximately <strong>~708,000 litres per month</strong>. This calculation illustrates why a staged storage plan is required for operational reliability.</p>
                    
                    <h3>Calculation Methodology (representative)</h3>
                    <ul>
                        <li>Monthly vessel calls (example): 35</li>
                        <li>Composition: Ferries 40% (14 calls) at 30,000 L per call = 420,000 L</li>
                        <li>Cargo vessels 30% (10 calls) at 20,000 L per call = 200,000 L</li>
                        <li>Fishing & small craft 30% (11 calls) at 8,000 L per call = 88,000 L</li>
                        <li><strong>Total ≈ 708,000 L per month (representative)</strong></li>
                    </ul>

                    <h2>Recommended Fuel Types & Storage Approach</h2>
                    <h3>Fuel Types (Phased Introduction):</h3>
                    <ul>
                      <li><strong>Phase 1: Marine Gasoil / Diesel (MGO/MDO):</strong> Recommended initial product due to wide use by ferries, fishing fleets, and cargo vessels. It requires no heating and has fewer operational complications.</li>
                      <li><strong>Phase 2: Intermediate/Heavy Fuel Oil (IFO/HFO):</strong> To be considered after MGO operations are established, as it requires more complex handling (e.g., heating coils).</li>
                    </ul>

                    <h3>Storage & Equipment Recommendations (Pilot Phase)</h3>
                    <ul>
                      <li><strong>Primary Tank:</strong> One double-walled aboveground modular steel tank, 60,000–75,000 L, certified for petroleum storage.</li>
                      <li><strong>Secondary (Redundant) Tank:</strong> One double-walled 25,000–30,000 L tank to provide operational redundancy.</li>
                      <li><strong>Containment:</strong> Tanks to be installed on a reinforced concrete slab with impermeable lining and a bunded secondary containment sized to ≥110% of the largest tank capacity (industry best practice).</li>
                      <li><strong>Fire Protection:</strong> Foam-capable firewater monitors, hydrants, and a trained fire response team.</li>
                    </ul>

                    <h3>Structural Design Notes:</h3>
                    <ul>
                      <li><strong>Slab Design:</strong> Reinforced concrete sized for tank load and dynamic loading, with perimeter drainage to an oil-water separator.</li>
                      <li><strong>Bund Walls:</strong> Engineered to resist hydrostatic pressure, with access for inspection and pump-out points.</li>
                      <li><strong>Electrical:</strong> Intrinsically safe fittings in hazardous areas, with proper grounding and bonding for all equipment.</li>
                    </ul>

                    <h2>Security, Safety & Regulatory Compliance Checklist</h2>
                    <h3>Security Measures:</h3>
                    <ul>
                      <li>24/7 guarded perimeter with CCTV and floodlighting.</li>
                      <li>Tamper-evident valves, secure metering, and a digital inventory management system.</li>
                      <li>Coordination with municipal police, Coast Guard, and Port Authority for perimeter security.</li>
                    </ul>
                    <h3>Regulatory & Permitting (Principal Items):</h3>
                    <ul>
                      <li>Port approvals and site designation from the National Ports Authority (NPA).</li>
                      <li>Environmental Compliance Certificate (ECC) from the Department of Environmental Resources (DER).</li>
                      <li>Fire safety compliance and permits from the Bureau of Fire Protection (BFP).</li>
                      <li>Customs coordination for imported fuel supplies.</li>
                      <li>Adherence to MARPOL/IMO guidelines for oil handling and pollution prevention.</li>
                    </ul>

                    <h2>Costs, 12-Month Pilot Timeline & Operations</h2>
                    <h3>Estimated Capital Costs (Phase 1 - pilot)</h3>
                    <table>
                        <thead>
                            <tr><th>Item</th><th>Cost (USD)</th></tr>
                        </thead>
                        <tbody>
                            <tr><td>Civil works (slab, bunding, access)</td><td>$150,000 – $200,000</td></tr>
                            <tr><td>Modular tanks + piping + pumps</td><td>$250,000 – $400,000</td></tr>
                            <tr><td>Fire protection, spill response</td><td>$60,000 – $100,000</td></tr>
                            <tr><td>Security, CCTV, fencing, lighting</td><td>$40,000 – $60,000</td></tr>
                            <tr><td>Contingency & commissioning (10–15%)</td><td>$50,000 – $90,000</td></tr>
                            <tr><td><strong>Estimated Phase 1 total</strong></td><td><strong>$550,000 – $850,000</strong></td></tr>
                        </tbody>
                    </table>
                    
                    <h3>Estimated Annual OPEX (pilot)</h3>
                     <ul>
                      <li><strong>Security & staffing:</strong> USD 60,000 – 90,000/year</li>
                      <li><strong>Utilities & maintenance:</strong> USD 20,000 – 40,000/year</li>
                      <li><strong>Insurance, certification & compliance:</strong> USD 30,000 – 50,000/year</li>
                    </ul>

                    <h3>12-Month Pilot Timeline (High-Level)</h3>
                    <ul>
                        <li><strong>Months 1-2:</strong> Site selection, NPA site clearance, preliminary environmental scoping.</li>
                        <li><strong>Months 3-4:</strong> Detailed engineering, procurement planning.</li>
                        <li><strong>Months 5-7:</strong> Civil works (slab, bunding) and security preparations.</li>
                        <li><strong>Months 8-9:</strong> Delivery and installation of modular tanks, pumps, and fire systems.</li>
                        <li><strong>Months 10-11:</strong> Commissioning, calibration, trial operations, staff training.</li>
                        <li><strong>Month 12:</strong> Full pilot operations and performance review; prepare Phase 2 expansion plan if KPIs met.</li>
                    </ul>

                    <h2>Next Steps & Recommendation</h2>
                    <p>We recommend the following phased approach to move this initiative forward:</p>
                    <ol className="list-decimal list-outside ml-6 space-y-2">
                        <li><strong>Approve a joint scoping visit:</strong> A technical team, alongside the Mayor's office, NPA, and Coast Guard, should inspect shortlisted sites.</li>
                        <li><strong>Commission feasibility study:</strong> A focused EIA/IEE and engineering study (4–6 weeks) should be conducted post-visit.</li>
                        <li><strong>Finalize commercial terms:</strong> Negotiate and agree upon site lease, operating license, and permit obligations.</li>
                        <li><strong>Target pilot commissioning:</strong> Aim for commissioning within 12 months of agreement signature.</li>
                    </ol>

                </div>
            </div>

            <div className="mt-8 text-center">
                <button 
                    onClick={() => onViewChange('report')}
                    className="bg-gradient-to-r from-nexus-accent-gold to-nexus-accent-gold-dark text-white font-bold py-3 px-8 rounded-xl text-lg shadow-lg shadow-nexus-accent-gold/30 hover:shadow-xl hover:shadow-nexus-accent-gold/50 transition-all duration-300 transform hover:scale-105 focus:outline-none focus:ring-4 focus:ring-nexus-accent-gold/50 flex items-center gap-3 mx-auto"
                >
                    <BlueprintIcon className="w-6 h-6" />
                    Generate Your Own Blueprint
                </button>
            </div>
            
            <button
                onClick={scrollTop}
                className={`back-to-top-btn ${showScroll ? 'visible' : ''}`}
                aria-label="Back to top"
            >
                <ArrowUpIcon className="w-6 h-6" />
            </button>
        </div>
    );
};
